### ISSUE TITLE
2018-01-30: Pescador 2.0 and NEMISIG recap

### ISSUE THREAD

**Issue by bmcfee** [marl/group_meetings#1]
What do people want to talk about?

**Comment by bmcfee** [comment]
Since nobody else has volunteered, I propose the following agenda:

1. Pescador 2.0 tutorial
2. NEMISIG'18 recap
3. Discuss ideas for readings?

**Comment by mcartwright** [comment]
I can't remember what format we decided on? Did we decide to dive deep on some topics? I recall  j-sal suggesting to look at some of the primary attention papers, e.g. https://arxiv.org/pdf/1409.0473.pdf

**Comment by mcartwright** [comment]
Ohh crap. Bmac beat me to it.

**Comment by mcartwright** [comment]
(I'm fine with the proposed agenda too)

**Comment by bmcfee** [comment]
@mcartwright want to add that paper (and others) over on #2 ?
