### ISSUE TITLE
2018-02-13 Plan

### ISSUE THREAD

**Issue by bmcfee** [marl/group_meetings#5]
We didn't settle on reading for this week, so instead let's do a round of project updates and a bit of planning toward various submissions.  Points to discuss:

- SPM article(s)
- ISMIR paper submissions
- ISMIR tutorial submissions
- ???

**Comment by lostanlen** [comment]
I will say a word about my work on twelve-tone scattering for composer recognition. I want to turn it into an ISMIR paper. I hope I find the time to do this in addition to BirdVox. I have the code and most of the results so now it would a matter of writing, finding appropriate references, and making cool figures. Co-author(s) welcome.

I would also like to discuss the possibility of turning the "urban orchestra" NEMISIG hackathon with @yw3004, @jtcramer, and @tomxi into a ISMIR demo. We have a repo for it: github.com/marl/urban-orchestra and it would be good if we could set up a agenda + distribution of roles for it.

**Comment by lostanlen** [comment]
The twelve-tone scattering paper has found a co-author 😌
